### ISSUE TITLE
Mirrors and reflections are broken in Studio

### ISSUE THREAD

**Issue by Clo363** [IllusionMods/KKS_VR#44]
Mirrors and reflections are opposite in Studio, while they are OK in official game VR.

**Comment by ManlyMarco** [comment]
Possibly fixed by #49

Can you test if this build fixes the issue? [KKS_VR_v1.4.1_BETA.zip](https://github.com/user-attachments/files/17535937/KKS_VR_v1.4.1_BETA.zip) Maybe check if POV works too if you have some time.

**Comment by Clo363** [comment]
Sadly the mirrors in studio VR are not fixed. The right eye shows correct image, the left eye shows distorted image. To replicate load map with mirror, look at mirror. This sadly also affect any reflections on any surfaces.

**Comment by ManlyMarco** [comment]
Damn.

**Comment by Clo363** [comment]
Any ideas on how to fix this? I vanilla game VR mirrors work just fine. I wonder whats different in studio?

**Comment by ManlyMarco** [comment]
@Clo363 Most likely it's an issue with the shader used on those mirrors.

**Comment by Clo363** [comment]
> [@Clo363](https://github.com/Clo363) Most likely it's an issue with the shader used on those mirrors.

Any chanse to have it fixed? so annoying to remove all mirrors and reflectionns from scene to view it in Studio. I wonder why mirrors in main game are not broken. Do they use a different shader?
