### ISSUE TITLE
Protagonist female voice

### ISSUE THREAD

**Issue by Maddmann112233** [IllusionMods/KKS_VR#68]
Hi when i interacting with the protagonist body it has female moans when you touch it, it gets really annoying because when you have the controller besides you it will spam moans whenever you touch the controller and is there a way to remove the slapping sounds when you move the controller ?

**Comment by lotsofbears** [comment]
Fixed. Grab it at [pre-release](https://github.com/lotsofbears/KKS_VR_PR/releases) version or wait for [release](https://github.com/IllusionMods/KKS_VR/releases).

**Comment by Maddmann112233** [comment]
I tried the pre-release but issue persists i still hear female voice when touching the protagonist is there an options menu to change it ?

**Comment by lotsofbears** [comment]
Go into settings and disable reaction by gender

**Comment by Maddmann112233** [comment]
Thank you very much it's working
